[project]
name = "spaxi"
version = "0.1.0"
description = "A pixi-like end-user experience for Spack packages"
readme = {file = "README.org", content-type = "text/org"}
authors = [
    { name = "Brett Viren", email = "brett.viren@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "click>=8.4.2",
    "zstandard>=0.23",
    "tomli-w>=1.0",
]

[project.scripts]
spaxi = "spaxi.cli:main"

[dependency-groups]
dev = [
    "pytest>=8.0",
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["spaxi*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
